### ISSUE TITLE
Frequency correction

### ISSUE THREAD

**Issue by Cloolalang** [MZachmann/LightLora_Arduino#2]
Hey Mark,
I read with interest in your blog article;
_Improve Temperature Stability
It’s easy to improve the temperature stability of your LoRa systems_\

I am trying to optimise my RFM96 lora devices for a porject that requires longer range.
Im using the RadioHead library however there is no provision in that library for improving the frequency stability at low bandwidths.
I would be very interested to see your code for the temperature compensation that you  mentioned in your article.
If you are able to share, it would really help.
I looked at using TCXO Lora boards, but they are pretty costly compared to the basic RFM95/6 and RA-02.
I have been able to tune a pair to use 7.8KHz BW but they do drift.
Best Wishes
Patrick

**Comment by MZachmann** [comment]
Hi Patrick,
I don't put the frequency compensation code into the lora driver itself but instead in the higher level code by simply changing the target frequency. My systems have temperature sensors inside of them and the compensation scale and method are determined by measurement (heuristically) because each semtech module provider uses a different commercial crystal. In my work the relationship was linear and the code I use is simply:

// called every time the temperature drifts more than a degree
int32_t freqHz = tscale * (_LocalTemperature - 77);	// use 77 or 25C as reference
_MyLora.SetFrequency(baseFrequency + freqOffset + freqHz);

Where freqOffset is the measured error in the crystal frequency at 25C and tscale is the measured temperature scale factor.

Regards, Mark

**Comment by Cloolalang** [comment]
Thanks for your response Mark. Interesting that helps me, I can develop for the library here (RadioHead/Mysensors)
Today I used an RTL-SDR and HDSDR for PC to "tune up" a pair if RA-02 Lora modules using the RadioHead #define RFM95_FXOSC. (32*1000000ul), 
Radio No1: 32*999990ul
Radio No2: 32*999996ul
I only eye-balled it as its tricky to easily see the center of the wide-band chirp.
They seem happy talking in the lab (22'C) on 7,8KHz BW SF7.
Im going to have a good at characterizing them over a few degrees. 
Many Thanks
Patrick

**Comment by MZachmann** [comment]
Sure. If you have a chip choice the new SX1262 has a CW (continuous wave) transmit that sends a sine wave single frequency - which is really nice for calibrating and testing.
Mark

**Comment by Cloolalang** [comment]
Thanks Mark. I plan to take a look at the SX1262, I previously used this as well:
https://github.com/sergev/morse-beacon/blob/master/morse-beacon.ino

**Comment by MZachmann** [comment]
as an old ham the morse-code-via-lora is :)
anyway, thanks for the example
